### ISSUE TITLE
Signing nwjs helpers with company ID

### ISSUE THREAD

**Issue by banezaklan** [johansatge/nwjs-macappstore#1]
Hi, 
First, thanks for the guide! Good work!
I didn't follow this guide but another one, it's possible that it is yours as well.
I had problems when trying to sign nwjs helper files with the company ID. I think I was getting "ID mismatch" at some point, either when building the pkg or when trying to upload the app to the store, I can't remember now.

Anyhow, currently I am signing helpers with their own IDs like this:

codesign -s 64MR5B73ZY -i com.intel.nw.helper --entitlements ChildEntitlements.xml --deep "activecollab-timer.app/Contents/Frameworks/node-webkit Helper.app"

codesign -s 64MR5B73ZY -i com.intel.nw.helper.EH --entitlements ChildEntitlements.xml --deep "activecollab-timer.app/Contents/Frameworks/node-webkit Helper EH.app"

codesign -s 64MR5B73ZY -i com.intel.nw.helper.NP --entitlements ChildEntitlements.xml --deep "activecollab-timer.app/Contents/Frameworks/node-webkit Helper NP.app"

codesign -s 64MR5B73ZY -i com.a51.activecollab.timer --entitlements ParentEntitlements.xml --deep "activecollab-timer.app"

Without this I couldn't complete the process before. 
Did you have to change the IDs in helper's info.plists ?

**Comment by johansatge** [comment]
Hi,

you are true, thanks for pointing that out !

I have updated the **Signing the app** page. The code now looks like this:

``` bash
codesign --deep -s $IDENTITY -i io.nwjs.nw.helper --entitlements $CHILD_PLIST $APP_PATH"/Contents/Frameworks/nwjs Helper.app"

codesign --deep -s $IDENTITY -i io.nwjs.nw.helper.EH --entitlements $CHILD_PLIST $APP_PATH"/Contents/Frameworks/nwjs Helper EH.app"

codesign --deep -s $IDENTITY -i io.nwjs.nw.helper.NP --entitlements $CHILD_PLIST $APP_PATH"/Contents/Frameworks/nwjs Helper NP.app"

codesign --deep -s $IDENTITY -i $BUNDLE_ID --entitlements $PARENT_PLIST $APP_PATH
```

Feel free to reopen if needed !
